slam_toolbox:
  ros__parameters:
    use_lifecycle_manager: false
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    world_frame: map
    scan_topic: /scan
    mode: mapping
    scan_queue_size: 2